const $=id=>document.getElementById(id);const uid=()=>Math.random().toString(36).slice(2,10);const num=v=>Number.isFinite(Number(v))?Number(v):0;const round=(v,d=1)=>Math.round((num(v)+Number.EPSILON)*10**d)/10**d;const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const clone=x=>JSON.parse(JSON.stringify(x));

const FORMULAS=[
['S26lf',505.8,10.35,58.5,25.6,0,254,153,160,430,4.36,2.6],['hiQ สูตร 3',66.67,2.22,7.2,3.33,0,88,0,36,133.33,0,0],['Infratini',501,13,50,27,0,500,280,185,499,5,4.5],['NAN LF',505.8,10.35,58.5,25.6,0,254,153,160,430,4.36,2.6],['enfalac LF',520,10.9,55,28,0,600,400,240,600,8.5,5.2],['Panenteral',511,15.3,54.5,12.85,12.85,439,220,225,564,5,3.5],['Nutramigen',500,14,55,25,0,570,390,240,610,9,3.5],['Pepti',494,12,56,26,0,345,189,150,554,3.9,3.7],['Pepti gastro',515,14,53.4,13.65,13.65,390,218,144,507,6,3.9],['Neocate',483,13,52.5,24.5,0,475,341,189,525,7.3,5.3],['Pediasure 1+ complete vanilla',467,13.87,61.3,18.2,0,463,388,176,606,6.48,3.1],['Milnutri sure',467,13.33,57.8,20,0,533.3,266.7,155.6,600,3.3,3.3],['Bendera',454,18.5,62.4,13.8,1.2,242,253,356,494,4.7,6.8],['Ensure',428,15.6,57.4,14,0,450,270,360,670,2.4,4.7],['Boost optimum',456,19,53,18,0,393,214,168,548,6,4],['นมจืดโฟโมสต์ 225 ml',62.22,3.11,4.89,3.55,0,124.44,88.89,42.22,168.89,0,0],['นมจืดโฟร์โมสต์ ไขมันต่ำ 225 ml',44.44,3.11,4.89,1.11,0,106.67,88.89,40,0,.13,0],['นมจืดโฟโมสต์ ไขมัน 0% 225 ml',35.56,3.56,4.89,0,0,124.44,88.89,42.22,0,0,0],['นมกล่องโฟโมสต์ omega 369 180 ml',55.55,2.22,5.55,2.78,0,88.89,66.67,41.67,111.11,2.92,.5],['enfagrow สูตร 3 จืด 180 ml',66.67,3.33,6.1,3.33,0,133.33,88.89,22.2,127.78,1.67,.5],['นมไทยเดนมาร์กจืด 200 ml',65,3,4.5,3.5,0,120,0,35,0,0,0],['enfalac A+ mind pro สูตร 1',510,10.5,56,28,0,360,240,136,510,4.5,3.3],['enfalac A+ mind pro สูตร 2',470,15,57,21,0,520,290,188,490,6.1,3.5],['enfalac A+ smart+ สูตร 1',520,11,53,30,0,470,240,136,630,8.9,5.2],['enfalac A+ smart+ สูตร 2',450,15.1,62,15.6,0,490,360,165,640,6.2,3.6],['Dulac สูตร 1',501,10.1,60.7,24.2,0,307,178,153,446,4.8,3],['Dupro สูตร 2',469,14.2,60.1,19.1,0,422,292,144,521,5.2,3.3],['S26 SMA 360 smart care (ชมพู) สูตร 1',506,10.69,52.8,28,0,305,191,219,497,5.4,4.58],['S26 Promil สูตร 2',461.7,15.6,56.63,19.2,0,540,343,271,546,5.6,3.35],['S26 progress สูตร 3',446.43,14.88,57.05,17.37,0,396.8,297.6,310,347.2,5.58,2.23],['HiQ prebioproteq สูตร 1',488,10.2,56.1,24.8,0,299,175,120,452,4.8,3.1],['HiQ prebioproteq สูตร 2',470,14.8,58.9,19.5,0,432,292,148,534,5.3,3.4],['Lactogen 1',514,10.8,59.2,26,0,257,133,130,420,4.1,4.1],['Lactogen 2',486,14.6,57.85,21.8,0,490,369,317,520,5.5,3.5],['นมตราหมี เบบี สูตร 1',514,10.8,59.2,26,0,257,133,130,420,4.1,4.1],['นมตราหมี เบบี สูตร 2',486,15.3,57.15,21.8,0,510,295,290,400,5.2,3.6],['นมผงตราหมี รสจืด สูตร 3',444.4,11.1,61.1,16.7,0,666.7,222.2,125,0,6.25,2.5],['คาร์เนชั่น 1+ จืด',444.4,11.1,58.3,19.4,0,666.7,222.2,125,0,5.56,2.5],['dumex dugrow 180 ml',50,2.22,6.11,2.22,0,111.11,66.67,41.67,122.22,.83,.5],['breast milk',67.7,1,7,3.8,0,22.5,13,20,47.5,0,0],['นมตราหมีสูตร 3 180 ซีซี',61.1,2.22,6.1,2.78,0,88.89,66.67,33.33,111.11,0,0],['S26 LF',505.8,10.35,58.5,25.6,0,254,153,160,430,4.36,2.6]
];
const LIQUID_NAMES=new Set(FORMULAS.filter(r=>/\b(180|200|225)\s*(ml|ซีซี)/i.test(r[0])||r[0]==='breast milk'||r[0]==='hiQ สูตร 3').map(r=>r[0]));
const seedDB=FORMULAS.map(r=>({id:uid(),type:'formula',name:r[0],basis_value:100,basis_unit:LIQUID_NAMES.has(r[0])?'mL':'g',kcal:r[1],protein:r[2],cho:r[3],fat:r[4],mct:r[5],calcium:r[6],phosphorus:r[7],sodium:r[8],potassium:r[9],iron:r[10],zinc:r[11],source:'Excel seed'}));
seedDB.push(
{id:uid(),type:'modular',name:'Dextrin',basis_value:1,basis_unit:'g',kcal:4,protein:0,cho:1,fat:0,mct:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Excel seed'},
{id:uid(),type:'modular',name:'Sucrose',basis_value:1,basis_unit:'g',kcal:4,protein:0,cho:1,fat:0,mct:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Excel seed'},
{id:uid(),type:'modular',name:'Whey protein',basis_value:1,basis_unit:'g',kcal:4,protein:1,cho:0,fat:0,mct:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Excel seed'},
{id:uid(),type:'modular',name:'LCT oil',basis_value:1,basis_unit:'g',kcal:9,protein:0,cho:0,fat:1,mct:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Excel seed'},
{id:uid(),type:'modular',name:'MCT oil',basis_value:1,basis_unit:'g',kcal:8.3,protein:0,cho:0,fat:1,mct:1,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Excel seed'}
);


// Nutrition book exchange-list foods (Ramathibodi Nutrition Unit, March 2009).
// These are exchange-based values from the attached book, not Thai FCD composition values.
const BOOK_FOODS=[];
function bookFood(name,basis_value,basis_unit,kcal,protein,cho,fat,category,extra={}){BOOK_FOODS.push({id:uid(),type:'food',name,basis_value,basis_unit,kcal,protein,cho,fat,mct:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Nutrition book exchange list',category,...extra})}
// Milk: 1 exchange = CHO 12 g, protein 8 g; energy/fat vary by milk type.
bookFood('นมสดธรรมดา',240,'mL',150,8,12,8,'milk');
bookFood('นมสดพร่องมันเนย',240,'mL',120,8,12,5,'milk');
bookFood('นมสดขาดมันเนย',240,'mL',90,8,12,1,'milk');
bookFood('นมระเหย',120,'mL',150,8,12,8,'milk');
bookFood('นมผง',30,'g',150,8,12,8,'milk',{portions:[{amount:4,unit:'ช้อนโต๊ะ'}]});
bookFood('นมผงขาดมันเนย',30,'g',90,8,12,1,'milk',{portions:[{amount:4,unit:'ช้อนโต๊ะ'}]});
// Meat: book defines 1 exchange as 30 g cooked edible meat (or 40 g raw). Default calculation state is cooked.
const meatGroups={
  verylean:{kcal:35,fat:1,names:['ปลาช่อน','ปลากะพงขาว','ปลาใบขนุน','ปลาเนื้ออ่อน','ลูกชิ้นปลา','หอยแครง','กุ้งฝอย','สันในไก่','ปลาตาเดียว','ปลาทู','ปลาทรายแดง','ปลาหมอเทศ','ลูกชิ้นเนื้อ','หอยลาย','เนื้อปูทะเล','เนื้อปูอบไม่ติดหนัง','ปลาเก๋า','ปลาหางเหลือง','ปลาดุกอุย','ปลากระบอก','ปลาหมึกกล้วย/ยักษ์','กุ้งทะเล','ปูตัวเล็ก','ปลานกแก้ว','ปลาสลิด','ปลาน้ำดอกไม้','ปลาอินทรีย์','หอยเชลล์','กุ้งน้ำจืด','อกไก่'],label:'เนื้อสัตว์ไขมันต่ำมาก'},
  lean:{kcal:55,fat:3,names:['เนื้อไก่','ปีกไก่','เนื้อสันขา/น่อง','เป็ดย่างไม่มีหนัง'],label:'เนื้อสัตว์ไขมันต่ำ'},
  medium:{kcal:75,fat:5,names:['เนื้อหมูป่า','หมูขาไม่ติดมัน','เป็ดเนื้อไม่มีหนัง','เต้าหู้แข็ง','หมูย่างไม่มีหนัง','หมูเนื้อไม่มีมัน','ไข่เป็ด','ไข่ไก่','เต้าหู้อ่อน (หลอด)'],label:'เนื้อสัตว์ไขมันปานกลาง'},
  high:{kcal:100,fat:8,names:['ปลาสวาย','ไส้กรอกหมู/ไก่','หมูย่าง (เนื้อและหนัง)','หนังหมู','เป็ด (เนื้อและหนัง)','กุนเชียง','หมู/ซี่โครงติดมัน','เนื้อวัวติดมัน','หมูเนื้อติดมัน','หมูแผ่น','หมูยอ','ไก่ (เนื้อและหนัง)','หมูบด','แฮม','แหนม'],label:'เนื้อสัตว์ไขมันสูง'}
};
Object.values(meatGroups).forEach(g=>g.names.forEach(n=>bookFood(n,30,'g',g.kcal,7,0,g.fat,'meat',{state:'cooked',exchange_group:g.label})));
// Whole eggs are listed in the medium-fat group; the book notes ~50 g/egg. Keep a household portion too.
BOOK_FOODS.filter(f=>['ไข่ไก่','ไข่เป็ด'].includes(f.name)).forEach(f=>f.portions=[{amount:1,unit:'ฟอง'}]);
// Rice / starch / cereal: 1 exchange = 80 kcal, CHO 18 g, protein 2 g.
// IMPORTANT: basis uses the exchange household measure printed in Nutrition book; do not invent a gram basis.
bookFood('ข้าวสวย',1,'ทัพพี',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:0.5,unit:'ถ้วยตวง'},{amount:8,unit:'ช้อนโต๊ะ'}]});
bookFood('ข้าวซ้อมมือ',1,'ทัพพี',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:0.5,unit:'ถ้วยตวง'},{amount:8,unit:'ช้อนโต๊ะ'}]});
bookFood('ข้าวเหนียวนึ่ง',0.25,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:4,unit:'ช้อนโต๊ะ'}]});
bookFood('ขนมจีน',1,'จับใหญ่',80,2,18,0,'rice_starch');
bookFood('เส้นหมี่ขาวลวก',0.75,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:10,unit:'ช้อนโต๊ะ'}]});
bookFood('บะหมี่สุก (ลวก 1 ก้อน)',2/3,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:8,unit:'ช้อนโต๊ะ'}]});
bookFood('มักกะโรนีสุก',2/3,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:8,unit:'ช้อนโต๊ะ'}]});
bookFood('สปาเกตตีสุก',2/3,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:8,unit:'ช้อนโต๊ะ'}]});
bookFood('บะหมี่สำเร็จรูปแห้ง',1/3,'ห่อ',80,2,18,0,'rice_starch');
bookFood('วุ้นเส้นลวก',10,'ช้อนโต๊ะ',80,2,18,0,'rice_starch',{state:'cooked'});
bookFood('สาคูสุก',5,'ช้อนโต๊ะ',80,2,18,0,'rice_starch',{state:'cooked'});
bookFood('มันฝรั่งต้ม',0.75,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:10,unit:'ช้อนโต๊ะ'}]});
bookFood('เผือกต้ม',0.5,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:6,unit:'ช้อนโต๊ะ'}]});
bookFood('มันเทศต้ม',0.5,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:6,unit:'ช้อนโต๊ะ'}]});
bookFood('ข้าวโพดต้ม',0.5,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked',portions:[{amount:0.5,unit:'ฝัก'}]});
bookFood('ถั่วเมล็ดแห้งสุก',0.5,'ถ้วยตวง',80,2,18,0,'rice_starch',{state:'cooked'});
bookFood('มันแกว',0.5,'ถ้วยตวง',80,2,18,0,'rice_starch',{portions:[{amount:1,unit:'หัวเล็ก'}]});
bookFood('ขนมปังขาว',1,'แผ่น',80,2,18,0,'rice_starch');
bookFood('ขนมปังโฮลวีท',1,'แผ่น',80,2,18,0,'rice_starch');
bookFood('ขนมปังกรอบ/แครกเกอร์',1,'แผ่นใหญ่',80,2,18,0,'rice_starch',{portions:[{amount:2,unit:'แผ่นเล็ก'}]});
// Fruit: 1 exchange = 60 kcal, CHO 15 g. Portion sizes follow the book.
[
 ['กล้วยไข่',1,'ผลกลาง'],['กล้วยน้ำว้า',1,'ผลกลาง'],['กล้วยหอม',1,'ผลเล็ก'],['กล้วยหักมุก',0.5,'ผลใหญ่'],['แคนตาลูป',0.25,'ผลกลาง'],['เงาะ',4,'ผลใหญ่'],['ชมพู่',4,'ผลใหญ่'],['แตงโม',0.25,'ผลกลาง'],['ทุเรียน',1,'เม็ดกลาง'],['ฝรั่ง',0.5,'ผลกลาง'],['มะม่วงดิบ',0.5,'ผลใหญ่'],['มะม่วงสุก',0.5,'ผลกลาง'],['มะละกอสุก',8,'ชิ้นขนาดคำ'],['ส้มเขียวหวาน',2,'ผลกลาง'],['ส้มโอ',2,'กลีบใหญ่'],['สับปะรด',8,'ชิ้นขนาดคำ'],['องุ่น',20,'ผลกลาง'],['แอปเปิล',1,'ผลเล็ก']
].forEach(x=>bookFood(x[0],x[1],x[2],60,0,15,0,'fruit'));
seedDB.push(...BOOK_FOODS);


const PORTION_DB=[
 {food:'ข้าวสวย',aliases:['ข้าว','ข้าวสวย','ข้าวหอมมะลิ'],state:'cooked',unit:'ทัพพี',g_per_unit:55,source:'อาหารแลกเปลี่ยน'},
 {food:'ข้าวกล้อง',aliases:['ข้าวกล้อง'],state:'cooked',unit:'ทัพพี',g_per_unit:55,source:'อาหารแลกเปลี่ยน'},
 {food:'เนื้อสัตว์สุก',aliases:['เนื้อไก่สุก','อกไก่สุก','สะโพกไก่สุก','หมูสุก','เนื้อหมูสุก','เนื้อปลาสุก'],state:'cooked',unit:'ช้อนโต๊ะ',g_per_unit:15,source:'อาหารแลกเปลี่ยน'},
 {food:'กล้วยน้ำว้า',aliases:['กล้วยน้ำว้า'],state:'edible',unit:'ผลกลาง',g_per_unit:45,source:'อาหารแลกเปลี่ยน'},
 {food:'แอปเปิล',aliases:['แอปเปิล'],state:'edible',unit:'ผลเล็ก',g_per_unit:100,source:'อาหารแลกเปลี่ยน'}
];
function blankCase(){return {id:uid(),patient:{alias:'',age:'',sex:'',visitDate:'',weight:'',height:'',note:''},requirements:{fluid:'',energy:'',protein:'',fatPct:'',mctPct:'',calcium:''},pnif:{},meals:[],modular:{name:'Daily modular recipe',finalVolume:'',notes:'',components:[],feeds:[],route:'',durationHr:''},lastSummary:null,updatedAt:new Date().toISOString()}}
const defaultState={patient:{alias:'',age:'',sex:'',visitDate:'',weight:'',height:'',note:''},requirements:{fluid:'',energy:'',protein:'',fatPct:'',mctPct:'',calcium:''},settings:{defaultSource:'Custom',needsReviewOnly:false},pnif:{},meals:[],modular:{name:'Daily modular recipe',finalVolume:'',notes:'',components:[],feeds:[],route:'',durationHr:''},foodDB:seedDB,portionDB:PORTION_DB,cases:[],activeCaseId:'',lastSummary:null};
let state=loadState(),deferredInstallPrompt=null;
function loadState(){try{const x=localStorage.getItem('pedNutritionStateV4')||localStorage.getItem('pedNutritionStateV3');const st=x?merge(defaultState,JSON.parse(x)):clone(defaultState);if(!st.settings.defaultSourceV042){st.settings.defaultSource='Custom';st.settings.defaultSourceV042=true;}if(!st.settings.bookFoodSeedV044){const keys=new Set((st.foodDB||[]).map(f=>(f.name+'|'+f.source).toLowerCase()));BOOK_FOODS.forEach(f=>{const k=(f.name+'|'+f.source).toLowerCase();if(!keys.has(k))st.foodDB.push(clone(f));});st.settings.bookFoodSeedV044=true;}if(!st.settings.bookBasisFixV045){
  const legacy=new Set(['เนื้อสัตว์ไขมันต่ำ 1 ส่วน|Excel seed','เนื้อสัตว์ไขมันปานกลาง 1 ส่วน|Excel seed','เนื้อสัตว์ไขมันสูง 1 ส่วน|Excel seed','ข้าวสวย (exchange)|Excel seed'].map(x=>x.toLowerCase()));
  st.foodDB=(st.foodDB||[]).filter(f=>!legacy.has(((f.name||'')+'|'+(f.source||'')).toLowerCase()) && f.source!=='Nutrition book exchange list');
  BOOK_FOODS.forEach(f=>st.foodDB.push(clone(f)));
  st.settings.bookBasisFixV045=true;
}
if(!st.settings.cookedDefaultV044){(st.meals||[]).forEach(m=>{m.raw_cooked=defaultFoodState(m.food,m.raw_cooked);(m.ingredients||[]).forEach(i=>i.raw_cooked=defaultFoodState(i.food,i.raw_cooked));});st.settings.cookedDefaultV044=true;}if(!st.cases.length){const c=blankCase();c.patient=clone(st.patient);c.requirements=clone(st.requirements);c.pnif=clone(st.pnif);c.meals=clone(st.meals);c.modular=clone(st.modular);c.lastSummary=st.lastSummary;st.cases=[c];st.activeCaseId=c.id}return st}catch{return clone(defaultState)}}function merge(a,b){const out=clone(a);Object.keys(b||{}).forEach(k=>out[k]=(typeof b[k]==='object'&&!Array.isArray(b[k])&&b[k]!==null)?{...(out[k]||{}),...b[k]}:b[k]);return out}function syncActiveCase(){let c=state.cases.find(x=>x.id===state.activeCaseId);if(!c)return;c.patient=clone(state.patient);c.requirements=clone(state.requirements);c.pnif=clone(state.pnif);c.meals=clone(state.meals);c.modular=clone(state.modular);c.lastSummary=state.lastSummary;c.updatedAt=new Date().toISOString()}function saveState(){syncActiveCase();localStorage.setItem('pedNutritionStateV4',JSON.stringify(state))}

function showTab(name){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===`tab-${name}`));if(name==='patient')renderPatient();if(name==='review')renderMeals();if(name==='modular')renderModular();if(name==='foods')renderFoodDB();if(name==='summary')renderSummary();if(name==='data')$('defaultSource').value=state.settings.defaultSource||'Custom'}document.querySelectorAll('[data-tab]').forEach(x=>x.addEventListener('click',()=>showTab(x.dataset.tab)));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').classList.add('hidden')});if('serviceWorker' in navigator) window.addEventListener('load', async()=>{
  try {
    // 0.4.5 cache recovery: preserve app data (localStorage/IndexedDB), remove only SW registrations and Cache Storage.
    const marker='pedNutritionCacheRecovery045';
    if(!sessionStorage.getItem(marker)){
      const regs=await navigator.serviceWorker.getRegistrations();
      await Promise.all(regs.map(r=>r.unregister()));
      if('caches' in window){ const keys=await caches.keys(); await Promise.all(keys.map(k=>caches.delete(k))); }
      sessionStorage.setItem(marker,'1');
      const u=new URL(location.href); u.searchParams.set('appv','0.4.5');
      location.replace(u.toString());
      return;
    }
    const reg=await navigator.serviceWorker.register('./sw.js?v=0.4.5',{updateViaCache:'none'});
    await reg.update();
  } catch(e){ console.warn('Service worker recovery/update failed',e); }
});

function loadCase(id){syncActiveCase();const c=state.cases.find(x=>x.id===id);if(!c)return;state.activeCaseId=id;state.patient=clone(c.patient);state.requirements=clone(c.requirements);state.pnif=clone(c.pnif);state.meals=clone(c.meals);state.modular=clone(c.modular);state.lastSummary=c.lastSummary;localStorage.setItem('pedNutritionStateV4',JSON.stringify(state));renderPatient();renderMeals();renderModular()}
function renderCaseSelector(){const el=$('caseSelector');if(!el)return;el.innerHTML=state.cases.map(c=>`<option value="${c.id}">${esc(c.patient.alias||'Untitled case')} ${c.patient.visitDate?'• '+esc(c.patient.visitDate):''}</option>`).join('');el.value=state.activeCaseId}
function newCase(){syncActiveCase();const c=blankCase();state.cases.push(c);state.activeCaseId=c.id;state.patient=clone(c.patient);state.requirements=clone(c.requirements);state.pnif={};state.meals=[];state.modular=clone(c.modular);state.lastSummary=null;saveState();renderPatient();renderMeals();renderModular();showTab('patient')}
function renderPatient(){renderCaseSelector();const p=state.patient,r=state.requirements;['Alias','Age','Sex','VisitDate','Weight','Height','Note'].forEach(k=>{const el=$('patient'+k);if(el)el.value=p[k.charAt(0).toLowerCase()+k.slice(1)]||''});$('reqFluid').value=r.fluid||'';$('reqEnergy').value=r.energy||'';$('reqProtein').value=r.protein||'';$('reqFatPct').value=r.fatPct||'';$('reqMctPct').value=r.mctPct||'';$('reqCalcium').value=r.calcium||'';const w=num(p.weight),h=num(p.height),bmi=w&&h?w/(h/100)**2:0;$('patientSummary').innerHTML=`<div class="summary-grid"><div class="metric">Case<b>${esc(p.alias||'—')}</b></div><div class="metric">Age / Sex<b>${esc(p.age||'—')} ${p.age?'y':''} ${esc(p.sex||'')}</b></div><div class="metric">Weight<b>${w?round(w,2)+' kg':'—'}</b></div><div class="metric">Length / Height<b>${h?round(h,1)+' cm':'—'}</b></div><div class="metric">BMI<b>${bmi?round(bmi,2)+' kg/m²':'—'}</b></div></div>`;$('requirementSummary').innerHTML=`<div class="summary-grid"><div class="metric">Fluid<b>${r.fluid?esc(r.fluid)+' mL/day':'—'}</b>${w&&r.fluid?`<span>${round(num(r.fluid)/w,1)} mL/kg/day</span>`:''}</div><div class="metric">Energy<b>${r.energy?esc(r.energy)+' kcal/day':'—'}</b>${w&&r.energy?`<span>${round(num(r.energy)/w,1)} kcal/kg/day</span>`:''}</div><div class="metric">Protein<b>${r.protein?esc(r.protein)+' g/day':'—'}</b>${w&&r.protein?`<span>${round(num(r.protein)/w,2)} g/kg/day</span>`:''}</div><div class="metric">Total fat<b>${r.fatPct?esc(r.fatPct)+'% energy':'—'}</b></div><div class="metric">MCT<b>${r.mctPct?esc(r.mctPct)+'% energy':'—'}</b></div><div class="metric">Calcium<b>${r.calcium?esc(r.calcium)+' mg/day':'—'}</b></div></div>`}
function savePatientForm(){state.patient={alias:$('patientAlias').value.trim(),age:$('patientAge').value,sex:$('patientSex').value,visitDate:$('patientVisitDate').value,weight:$('patientWeight').value,height:$('patientHeight').value,note:$('patientNote').value};state.requirements={fluid:$('reqFluid').value,energy:$('reqEnergy').value,protein:$('reqProtein').value,fatPct:$('reqFatPct').value,mctPct:$('reqMctPct').value,calcium:$('reqCalcium').value};saveState();renderPatient()}$('savePatientBtn').addEventListener('click',savePatientForm);['patientAlias','patientAge','patientSex','patientVisitDate','patientWeight','patientHeight','patientNote','reqFluid','reqEnergy','reqProtein','reqFatPct','reqMctPct','reqCalcium'].forEach(id=>$(id).addEventListener('change',savePatientForm));$('caseSelector').addEventListener('change',e=>loadCase(e.target.value));$('newCaseBtn').addEventListener('click',newCase);

function normAmt(v){if(v===null||v===undefined||v==='')return{value:'',original:''};if(typeof v==='number')return{value:v,original:String(v)};const s=String(v).trim();const frac=s.match(/^(\d+)\s*\/\s*(\d+)$/);if(frac)return{value:Number(frac[1])/Number(frac[2]),original:s};const mixed=s.match(/^(\d+)\s+(\d+)\s*\/\s*(\d+)$/);if(mixed)return{value:Number(mixed[1])+Number(mixed[2])/Number(mixed[3]),original:s};const range=s.match(/^(\d+(?:\.\d+)?)\s*[-–]\s*(\d+(?:\.\d+)?)$/);if(range)return{value:round((+range[1]+ +range[2])/2,2),original:s};const n=Number(s);return{value:Number.isFinite(n)?n:s,original:s}}
function isMeatOrEgg(name=''){return /(ไก่|หมู|เนื้อ|ปลา|กุ้ง|ปู|หอย|เป็ด|ไข่|ตับ|กึ๋น|แฮม|แหนม|ไส้กรอก|ลูกชิ้น)/i.test(name)}function defaultFoodState(name,stateValue){return stateValue&&stateValue!=='unknown'?stateValue:(isMeatOrEgg(name)?'cooked':'unknown')}
function normIng(i={}){const a=normAmt(i.amount),food=i.food||i.name||'';return{id:i.id||uid(),food,amount:a.value,original_amount:a.original,unit:i.unit||'',weight_g:i.weight_g??'',volume_ml:i.volume_ml??'',raw_cooked:defaultFoodState(food,i.raw_cooked),confidence:i.confidence||'medium',note:i.note||'',dbMatchId:i.dbMatchId||'',convertFood:i.convertFood||'',convertUnit:i.convertUnit||''}}
function normItem(i={}){const a=normAmt(i.amount),food=i.food||i.name||'';return{id:i.id||uid(),time:i.time||'',food,amount:a.value,original_amount:a.original,unit:i.unit||'',weight_g:i.weight_g??'',volume_ml:i.volume_ml??'',raw_cooked:defaultFoodState(food,i.raw_cooked),confidence:i.confidence||'medium',needs_review:Boolean(i.needs_review||i.confidence==='low'),note:i.note||'',ingredients:(i.ingredients||[]).map(normIng),calcMethod:i.calcMethod||'auto',dbMatchId:i.dbMatchId||'',sourcePreference:i.sourcePreference||state.settings.defaultSource||'Custom',editOpen:false}}
function extractJson(text){const f=text.match(/```(?:json)?\s*([\s\S]*?)```/i);if(f)text=f[1];const a=text.indexOf('{'),b=text.lastIndexOf('}');if(a<0||b<=a)throw new Error('ไม่พบ JSON object');return JSON.parse(text.slice(a,b+1))}
function importPnif(){try{const o=extractJson($('pnifInput').value),type=o.type||'24hr_recall';state.pnif={format:o.format||'PNIF',version:o.version||'',type,warnings:o.warnings||[]};if(['daily_modular_recipe','modular_recipe'].includes(type)){importModular(o);$('pnifStatus').className='status ok';$('pnifStatus').textContent='Import modular diet สำเร็จ — เปิดหน้า Modular Diet เพื่อตรวจ/แก้';saveState();showTab('modular');return}if(!Array.isArray(o.items))throw new Error('PNIF ประเภท intake ต้องมี items[]');state.meals=o.items.map(normItem);sortMeals();saveState();$('pnifStatus').className='status ok';$('pnifStatus').textContent=`Import สำเร็จ ${state.meals.length} รายการ`;showTab('review')}catch(e){$('pnifStatus').className='status error';$('pnifStatus').textContent='Import ไม่สำเร็จ: '+e.message}}
function importModular(o){const comps=(o.ingredients||[]).map(x=>{const a=normAmt(x.amount);return{id:uid(),name:x.food||x.name||'',amount:a.value,unit:x.unit||'',dbMatchId:'',source:'Custom',kcalOverride:'',proteinOverride:'',fatOverride:'',mctOverride:'',choOverride:'',calciumOverride:'',sodiumOverride:'',potassiumOverride:'',note:x.note||''}});const fp=o.feeding_plan||{},actual=o.actual_intake?.feeds||[];let feeds=[];if(actual.length)feeds=actual.map((x,i)=>({id:uid(),time:x.time||'',prescribed:x.prescribed_ml??fp.volume_per_feed_ml??'',actual:x.actual_ml??'',note:x.note||''}));else if(fp.feeds_per_day){for(let i=0;i<num(fp.feeds_per_day);i++)feeds.push({id:uid(),time:'',prescribed:fp.volume_per_feed_ml??'',actual:'',note:''})}state.modular={name:o.recipe_name||'Daily modular recipe',finalVolume:o.preparation?.final_volume_ml??o.final_volume_ml??'',notes:(o.warnings||[]).join(' | '),components:comps,feeds,route:fp.route||'',durationHr:fp.duration_hr_per_feed??''}}
$('importPnifBtn').addEventListener('click',importPnif);$('clearPnifBtn').addEventListener('click',()=>{$('pnifInput').value='';$('pnifStatus').textContent=''});$('loadExampleBtn').addEventListener('click',()=>{$('pnifInput').value=JSON.stringify({format:'PNIF',version:'0.3',type:'24hr_recall',items:[{time:'12:00',food:'ข้าวผัด',amount:'3/4',unit:'จาน',ingredients:[],confidence:'high'},{time:'15:00',food:'ผลไม้',amount:null,unit:null,confidence:'medium',needs_review:true}]},null,2)});

function sortMeals(){state.meals.sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));saveState()}function hasPortion(x){return x.weight_g!==''||x.volume_ml!==''||x.amount!==''}function portionText(x){if(x.weight_g!=='')return `${x.weight_g} g`;if(x.volume_ml!=='')return `${x.volume_ml} mL`;if(x.original_amount&&x.original_amount!==String(x.amount))return `${x.original_amount}${x.unit?' '+x.unit:''}`;return x.amount!==''?`${x.amount}${x.unit?' '+x.unit:''}`:''}function ingText(i){return `${i.food||'(ไม่ระบุ)'}${portionText(i)?' '+portionText(i):''}`}
function autoCalcRule(m){const quantified=(m.ingredients||[]).filter(hasPortion),allQuant=m.ingredients.length>0&&quantified.length===m.ingredients.length,menuPortion=hasPortion(m);if(!m.ingredients.length)return menuPortion?{method:'whole',note:'Whole dish'}:{method:'none',note:'Portion missing'};if(!menuPortion){if(quantified.length)return{method:'ingredients',note:allQuant?'Ingredients':'Reported ingredients only — list may be incomplete'};return{method:'none',note:'Portion missing'};}if(allQuant)return{method:'ingredients',note:'Ingredients quantified; review if list is incomplete'};return{method:'whole',note:'Whole dish; incomplete ingredients kept as description'}}
function renderMeals(){const c=$('mealsContainer');c.innerHTML='';const filtered=state.settings.needsReviewOnly?state.meals.filter(m=>m.needs_review||autoCalcRule(m).method==='none'):state.meals;const groups={};filtered.forEach(m=>(groups[m.time||'No time']??=[]).push(m));const nReview=state.meals.filter(m=>m.needs_review||autoCalcRule(m).method==='none').length;$('reviewSummary').textContent=`${state.meals.length} items • ${nReview} need review`;$('needsReviewBtn').textContent=`Needs review only: ${state.settings.needsReviewOnly?'On':'Off'}`;$('reviewWarnings').innerHTML=(state.pnif.warnings||[]).length?`<div class="warning-box">${state.pnif.warnings.map(esc).join(' • ')}</div>`:'';Object.entries(groups).forEach(([time,items])=>{const card=document.createElement('div');card.className='time-card';card.innerHTML=`<div class="time-head"><span>${esc(time)}</span><button class="small-btn secondary add-time">+ Add item at this time</button></div>`;card.querySelector('.add-time').onclick=()=>{state.meals.push(normItem({time:time==='No time'?'':time,food:'',needs_review:true}));saveState();renderMeals()};items.forEach(m=>card.appendChild(menuNode(m)));c.appendChild(card)});if(!filtered.length)c.innerHTML='<p class="muted">ไม่มีรายการใน filter นี้</p>'}
function menuNode(m){const wrap=document.createElement('div');wrap.className='menu-row';const rule=m.calcMethod==='auto'?autoCalcRule(m):{method:m.calcMethod,note:'Manual selection'};const ing=(m.ingredients||[]).map(ingText);const shown=ing.slice(0,3).join(' • ')+(ing.length>3?` • +${ing.length-3} more`:'');wrap.innerHTML=`<div class="menu-main"><div><div class="menu-title">${esc(m.food||'(ยังไม่ได้ระบุเมนู)')} <span class="portion">${esc(portionText(m))}</span></div>${shown?`<div class="ingredients-line">ส่วนประกอบ: ${esc(shown)}</div>`:''}<div class="badges">${m.needs_review?'<span class="badge warn">Needs review</span>':''}<span class="badge">Calc: ${esc(rule.method)}</span>${rule.note?`<span class="badge ${rule.method==='none'?'warn':''}">${esc(rule.note)}</span>`:''}</div></div><div class="menu-actions"><button class="small-btn secondary edit">Edit</button><button class="small-btn secondary insert">Insert below</button><button class="small-btn danger del">Delete</button></div></div><div class="edit-slot"></div>`;wrap.querySelector('.edit').onclick=()=>{m.editOpen=!m.editOpen;renderMeals()};wrap.querySelector('.insert').onclick=()=>{const idx=state.meals.findIndex(x=>x.id===m.id);state.meals.splice(idx+1,0,normItem({time:m.time,food:'',needs_review:true}));saveState();renderMeals()};wrap.querySelector('.del').onclick=()=>{state.meals=state.meals.filter(x=>x.id!==m.id);saveState();renderMeals()};if(m.editOpen)wrap.querySelector('.edit-slot').appendChild(editPanel(m));return wrap}
function editPanel(m){const d=document.createElement('div');d.className='edit-panel';d.innerHTML=`<div class="edit-grid"><label>Time<input data-k="time" value="${esc(m.time)}"></label><label>Menu<input data-k="food" value="${esc(m.food)}"></label><label>Amount<input data-k="amount" value="${esc(m.amount)}"></label><label>Unit<input data-k="unit" value="${esc(m.unit)}"></label><label>Weight g<input data-k="weight_g" type="number" step="0.1" value="${esc(m.weight_g)}"></label><label>Volume mL<input data-k="volume_ml" type="number" step="0.1" value="${esc(m.volume_ml)}"></label><label>Calculation<select data-k="calcMethod"><option value="auto">Auto</option><option value="whole">Whole dish</option><option value="ingredients">Ingredients</option><option value="hybrid">Hybrid</option></select></label><label>Preferred source<select data-k="sourcePreference"><option>Thai FCD</option><option>Custom</option><option>USDA</option><option>All</option></select></label></div><div class="calc-note">หลัก: ไม่มี portion ของเมนูแต่มีส่วนประกอบที่มีปริมาณ → คำนวณส่วนที่รายงานได้; ไม่มีทั้ง portion และปริมาณส่วนประกอบ → ไม่เดาและไม่คำนวณรายการนั้น</div><div class="section-title-row top-gap"><strong>Ingredients</strong><button class="small-btn secondary add-ing">+ Ingredient</button></div><div class="ings"></div><label class="top-gap">Note<input data-k="note" value="${esc(m.note)}"></label><label><input data-k="needs_review" type="checkbox" ${m.needs_review?'checked':''}> Needs review</label>`;d.querySelector('[data-k="calcMethod"]').value=m.calcMethod||'auto';d.querySelector('[data-k="sourcePreference"]').value=m.sourcePreference||state.settings.defaultSource||'Custom';d.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.k;m[k]=el.type==='checkbox'?el.checked:el.value;if(k==='amount')m.original_amount=el.value;saveState();if(['time','food','amount','unit','weight_g','volume_ml','calcMethod','needs_review'].includes(k))renderMeals()}));const box=d.querySelector('.ings');(m.ingredients||[]).forEach(i=>box.appendChild(ingEditor(m,i)));d.querySelector('.add-ing').onclick=()=>{m.ingredients.push(normIng({}));saveState();renderMeals()};return d}
function portionOptions(food){const q=String(food||'').toLowerCase();return state.portionDB.filter(x=>x.food.toLowerCase().includes(q)||(x.aliases||[]).some(a=>a.toLowerCase().includes(q)||q.includes(a.toLowerCase())))}
function convertToGrams(x){if(x.weight_g!=='')return num(x.weight_g);if(String(x.unit).toLowerCase()==='g')return num(x.amount);const cf=x.convertFood||x.food,cu=x.convertUnit||x.unit,q=String(cf||'').toLowerCase();const hit=state.portionDB.find(r=>(r.food.toLowerCase()===q||(r.aliases||[]).some(a=>a.toLowerCase()===q))&&r.unit===cu);return hit&&x.amount!==''?num(x.amount)*num(hit.g_per_unit):null}
function conversionSelects(x){const foods=[...new Set(state.portionDB.map(r=>r.food))];const selected=x.convertFood||'';let units=[...new Set(state.portionDB.filter(r=>!selected||r.food===selected).map(r=>r.unit))];if(x.unit&&!units.includes(x.unit))units.unshift(x.unit);return `<label>Convert food ingredient<select data-k="convertFood"><option value="">—</option>${foods.map(v=>`<option ${x.convertFood===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label><label>Unit<select data-k="convertUnit"><option value="">—</option>${units.map(v=>`<option value="${esc(v)}" ${((x.convertUnit||x.unit)===v)?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function ingEditor(m,i){const g=convertToGrams(i);const r=document.createElement('div');r.className='ingredient-editor';r.innerHTML=`<label>Ingredient<input data-k="food" value="${esc(i.food)}"></label>${conversionSelects(i)}<label>Amount<input data-k="amount" value="${esc(i.original_amount||i.amount)}"></label><label>Reported unit<input data-k="unit" value="${esc(i.unit)}"></label><label>Calculated weight<input disabled value="${g!==null?round(g,1)+' g':'Needs conversion'}"></label><button class="small-btn danger">Delete</button>`;r.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{i[el.dataset.k]=el.value;if(el.dataset.k==='amount'){const a=normAmt(el.value);i.amount=a.value;i.original_amount=el.value}saveState();renderMeals()}));r.querySelector('button').onclick=()=>{m.ingredients=m.ingredients.filter(x=>x.id!==i.id);saveState();renderMeals()};return r}
$('addMealBtn').addEventListener('click',()=>{state.meals.push(normItem({needs_review:true}));saveState();renderMeals()});$('needsReviewBtn').addEventListener('click',()=>{state.settings.needsReviewOnly=!state.settings.needsReviewOnly;saveState();renderMeals()});

function exactCustom(name){const q=String(name||'').trim().toLowerCase();return state.foodDB.find(f=>f.name.trim().toLowerCase()===q)||state.foodDB.find(f=>f.name.toLowerCase().includes(q)||q.includes(f.name.toLowerCase()))}
function factorFor(x,f){const bu=String(f.basis_unit||'').toLowerCase(),xu=String(x.unit||'').toLowerCase();const cg=convertToGrams(x);if(cg!==null&&bu==='g')return cg/num(f.basis_value);if(x.volume_ml!==''&&bu==='ml')return num(x.volume_ml)/num(f.basis_value);if(xu===bu&&x.amount!=='')return num(x.amount)/num(f.basis_value);const hp=(f.portions||[]).find(p=>String(p.unit).toLowerCase()===xu);if(hp&&x.amount!=='')return num(x.amount)/num(hp.amount);return null}
const NUT=['kcal','protein','fat','mct','cho','calcium','phosphorus','sodium','potassium','iron','zinc'];function emptyNut(){return Object.fromEntries(NUT.map(k=>[k,0]))}function addNut(t,f,fac){NUT.forEach(k=>t[k]+=num(f[k])*fac)}
function calcPart(x,time,missing){const f=exactCustom(x.food);if(!f){missing.push({time,food:x.food,reason:'No Custom DB match / choose Thai FCD or USDA manually'});return null}const fac=factorFor(x,f);if(fac===null){missing.push({time,food:x.food,reason:`Need ${f.basis_unit} amount or matching unit`});return null}const t=emptyNut();addNut(t,f,fac);return t}
function calculateIntake(){const total=emptyNut(),missing=[];let calcItems=0;state.meals.forEach(m=>{let method=m.calcMethod==='auto'?autoCalcRule(m).method:m.calcMethod;let any=false;if(method==='none'){missing.push({time:m.time,food:m.food,reason:'Portion missing'});return}if(method==='whole'){const t=calcPart(m,m.time,missing);if(t){NUT.forEach(k=>total[k]+=t[k]);any=true}}else if(method==='ingredients'){(m.ingredients||[]).filter(hasPortion).forEach(i=>{const t=calcPart(i,m.time,missing);if(t){NUT.forEach(k=>total[k]+=t[k]);any=true}});if((m.ingredients||[]).some(i=>!hasPortion(i)))missing.push({time:m.time,food:m.food,reason:'Some ingredients have no portion; calculated reported components only'})}else if(method==='hybrid'){// no silent standard-recipe filling: use quantified ingredients only and flag remainder
(m.ingredients||[]).filter(hasPortion).forEach(i=>{const t=calcPart(i,m.time,missing);if(t){NUT.forEach(k=>total[k]+=t[k]);any=true}});missing.push({time:m.time,food:m.food,reason:'Hybrid: only reported quantified ingredients calculated; unreported remainder not estimated automatically'})}if(any)calcItems++});state.lastSummary={total,missing,calcItems,totalItems:state.meals.length,at:new Date().toISOString()};saveState();return state.lastSummary}
function nutGrid(t,prefix=''){return `<div class="summary-grid top-gap"><div class="metric">Energy<b>${prefix}${round(t.kcal)} kcal/day</b></div><div class="metric">Protein<b>${prefix}${round(t.protein)} g/day</b></div><div class="metric">Total fat<b>${prefix}${round(t.fat)} g/day</b></div><div class="metric">MCT<b>${prefix}${round(t.mct)} g/day</b></div><div class="metric">CHO<b>${prefix}${round(t.cho)} g/day</b></div><div class="metric">Ca<b>${prefix}${round(t.calcium)} mg</b></div><div class="metric">P<b>${prefix}${round(t.phosphorus)} mg</b></div><div class="metric">Na<b>${prefix}${round(t.sodium)} mg</b></div><div class="metric">K<b>${prefix}${round(t.potassium)} mg</b></div><div class="metric">Fe<b>${prefix}${round(t.iron)} mg</b></div><div class="metric">Zn<b>${prefix}${round(t.zinc)} mg</b></div></div>`}
function renderSummary(){const s=state.lastSummary||calculateIntake(),food=s.total,incomplete=s.missing.length>0,recipe=modularTotals(),vol=num(state.modular.finalVolume),act=state.modular.feeds.reduce((z,x)=>z+num(x.actual),0),pres=state.modular.feeds.reduce((z,x)=>z+num(x.prescribed),0),used=act||pres,ratio=vol?used/vol:0,mod=emptyNut();NUT.forEach(k=>mod[k]=recipe[k]*ratio);const total=emptyNut();NUT.forEach(k=>total[k]=food[k]+mod[k]);$('nutrientSummary').innerHTML=`${incomplete?`<div class="incomplete">Regular food intake incomplete • ${s.calcItems}/${s.totalItems} menu items contributed</div>`:''}<h3>1. From regular food</h3>${nutGrid(food,incomplete?'≥ ':'')}<h3 class="top-gap">2. From modular diet / medical formula</h3><p class="muted">${act?'Actual intake':'Prescribed intake used because actual mL is not entered'}: ${round(used)} mL/day</p>${nutGrid(mod)}<h3 class="top-gap">3. Total daily intake</h3>${nutGrid(total,incomplete?'≥ ':'')}${requirementCompare(total)}`;$('unmatchedList').innerHTML=s.missing.length?`<div class="unmatched"><strong>Not calculated / partial (${s.missing.length})</strong>${s.missing.map(x=>`<div>${esc(x.time||'—')} — ${esc(x.food||'(blank)')}: ${esc(x.reason)}</div>`).join('')}</div>`:'<div class="status ok">Regular food items calculated from available matched data.</div>'}
function requirementCompare(t){const r=state.requirements,w=num(state.patient.weight),a=[];if(r.fluid)a.push(`Fluid target ${esc(r.fluid)} mL/day`);if(r.energy)a.push(`Energy ${round(t.kcal/num(r.energy)*100,1)}% target`);if(r.protein)a.push(`Protein ${round(t.protein/num(r.protein)*100,1)}% target`);if(r.calcium)a.push(`Calcium ${round(t.calcium/num(r.calcium)*100,1)}% target`);if(w)a.push(`${round(t.kcal/w,1)} kcal/kg/day • ${round(t.protein/w,2)} g protein/kg/day`);return a.length?`<p class="muted top-gap"><strong>Requirement comparison:</strong> ${a.join(' • ')}</p>`:''}$('calculateBtn').addEventListener('click',()=>{calculateIntake();renderSummary()});

function renderFoodDB(){const body=$('foodDbBody');body.innerHTML='';const typ=$('dbTypeFilter').value||'all',q=($('dbSearch').value||'').toLowerCase();state.foodDB.filter(f=>(typ==='all'||f.type===typ)&&(!q||f.name.toLowerCase().includes(q))).forEach(f=>{const tr=document.createElement('tr');tr.innerHTML=`<td><select data-k="type"><option value="food">Food</option><option value="formula">Formula</option><option value="modular">Modular</option></select></td><td><input data-k="name" value="${esc(f.name)}"></td><td><input data-k="basis_value" type="number" value="${esc(f.basis_value)}" style="width:70px"><select data-k="basis_unit">${["g","mL","portion","ทัพพี","ถ้วยตวง","ช้อนโต๊ะ","ช้อนชา","ฟอง","ฝัก","หัวเล็ก","ผลกลาง","ผลเล็ก","ผลใหญ่","กลีบใหญ่","เม็ดกลาง","ชิ้นขนาดคำ","จับใหญ่","ห่อ","แผ่น","แผ่นเล็ก","แผ่นใหญ่"].map(u=>`<option>${u}</option>`).join("")}</select></td><td><input data-k="grams_per_scoop" type="number" step="0.01" value="${esc(f.grams_per_scoop||'')}"></td>${['kcal','protein','fat','mct','cho','calcium','phosphorus','sodium','potassium','iron','zinc'].map(k=>`<td><input data-k="${k}" type="number" step="0.01" value="${esc(f[k]||0)}"></td>`).join('')}<td><input data-k="source" value="${esc(f.source||'Custom')}"></td><td><button class="small-btn danger">Delete</button></td>`;tr.querySelector('[data-k="type"]').value=f.type;tr.querySelector('[data-k="basis_unit"]').value=f.basis_unit;tr.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{f[el.dataset.k]=el.value;saveState()}));tr.querySelector('button').onclick=()=>{state.foodDB=state.foodDB.filter(x=>x.id!==f.id);saveState();renderFoodDB()};body.appendChild(tr)})}
$('dbTypeFilter').addEventListener('change',renderFoodDB);$('dbSearch').addEventListener('input',renderFoodDB);$('addFoodDbBtn').addEventListener('click',()=>{state.foodDB.unshift({id:uid(),type:'food',name:'',basis_value:100,basis_unit:'g',kcal:0,protein:0,fat:0,mct:0,cho:0,calcium:0,phosphorus:0,sodium:0,potassium:0,iron:0,zinc:0,source:'Custom',grams_per_scoop:''});saveState();renderFoodDB()});

function blankComp(){return{id:uid(),name:'',amount:'',unit:'g',dbMatchId:'',source:'Custom',kcalOverride:'',proteinOverride:'',fatOverride:'',mctOverride:'',choOverride:'',calciumOverride:'',sodiumOverride:'',potassiumOverride:'',note:''}}function blankFeed(){return{id:uid(),time:'',prescribed:'',actual:'',note:''}}
function componentCalc(c){const f=exactCustom(c.name);if(f&&c.source==='Custom'){let amount=c.amount,unit=c.unit,weight='';if(String(unit).toLowerCase()==='scoop'&&f.grams_per_scoop){weight=num(amount)*num(f.grams_per_scoop);unit='g'}else if(unit==='g')weight=amount;const fac=factorFor({amount,unit,weight_g:weight,volume_ml:unit==='mL'?amount:''},f);if(fac!==null){const t=emptyNut();addNut(t,f,fac);return t}}const t=emptyNut();t.kcal=num(c.kcalOverride);t.protein=num(c.proteinOverride);t.fat=num(c.fatOverride);t.mct=num(c.mctOverride);t.cho=num(c.choOverride);t.calcium=num(c.calciumOverride);t.sodium=num(c.sodiumOverride);t.potassium=num(c.potassiumOverride);return t}
function modularTotals(){const t=emptyNut();state.modular.components.forEach(c=>{const x=componentCalc(c);NUT.forEach(k=>t[k]+=x[k])});return t}
function renderModular(){$('modName').value=state.modular.name||'';$('modFinalVolume').value=state.modular.finalVolume||'';$('modNotes').value=state.modular.notes||'';const c=$('modComponents');c.innerHTML='';state.modular.components.forEach(comp=>{const r=document.createElement('div');r.className='mod-row';r.innerHTML=`<label>Component<input data-k="name" value="${esc(comp.name)}"></label><label>Source<select data-k="source"><option>Custom</option><option>Thai FCD</option><option>USDA</option></select></label><label>Amount<input data-k="amount" type="number" step="0.1" value="${esc(comp.amount)}"></label><label>Unit<input data-k="unit" value="${esc(comp.unit)}" placeholder="g / mL / scoop"></label>${[["kcalOverride","Energy kcal"],["proteinOverride","Protein g"],["fatOverride","Total fat g"],["mctOverride","MCT g"],["choOverride","CHO g"],["calciumOverride","Ca mg"],["sodiumOverride","Na mg"],["potassiumOverride","K mg"]].map(([k,l])=>`<label>${l}<input data-k="${k}" type="number" step="0.1" value="${esc(comp[k]||'')}"></label>`).join('')}<button class="small-btn danger">Delete</button>`;r.querySelector('[data-k="source"]').value=comp.source||'Custom';r.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{comp[el.dataset.k]=el.value;saveState();renderModularSummary()}));r.querySelector('button').onclick=()=>{state.modular.components=state.modular.components.filter(x=>x.id!==comp.id);saveState();renderModular()};c.appendChild(r)});const f=$('feedSchedule');f.innerHTML='';state.modular.feeds.forEach(feed=>{const r=document.createElement('div');r.className='feed-row';r.innerHTML=`<label>Time<input data-k="time" value="${esc(feed.time)}"></label><label>Prescribed mL<input data-k="prescribed" type="number" value="${esc(feed.prescribed)}"></label><label>Actual mL<input data-k="actual" type="number" value="${esc(feed.actual)}"></label><label>% consumed<input disabled value="${feed.prescribed?round(num(feed.actual)/num(feed.prescribed)*100,1):0}%"></label><label>Note<input data-k="note" value="${esc(feed.note)}"></label><button class="small-btn danger">Delete</button>`;r.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('change',()=>{feed[el.dataset.k]=el.value;saveState();renderModular()}));r.querySelector('button').onclick=()=>{state.modular.feeds=state.modular.feeds.filter(x=>x.id!==feed.id);saveState();renderModular()};f.appendChild(r)});renderModularSummary()}
function renderModularSummary(){const t=modularTotals(),vol=num(state.modular.finalVolume),pres=state.modular.feeds.reduce((s,x)=>s+num(x.prescribed),0),act=state.modular.feeds.reduce((s,x)=>s+num(x.actual),0),ratio=vol?act/vol:0;$('modRecipeSummary').innerHTML=`<div class="summary-grid"><div class="metric">Recipe energy<b>${round(t.kcal)} kcal</b></div><div class="metric">Protein<b>${round(t.protein)} g</b></div><div class="metric">Fat<b>${round(t.fat)} g</b></div><div class="metric">MCT<b>${round(t.mct)} g</b></div><div class="metric">CHO<b>${round(t.cho)} g</b></div><div class="metric">Concentration<b>${vol?round(t.kcal/vol,3)+' kcal/mL':'—'}</b></div></div>`;$('feedSummary').innerHTML=`<div class="summary-grid"><div class="metric">Prescribed<b>${round(pres)} mL/day</b></div><div class="metric">Actual<b>${round(act)} mL/day</b></div><div class="metric">Consumed<b>${pres?round(act/pres*100,1):0}%</b></div><div class="metric">Actual energy<b>${round(t.kcal*ratio)} kcal</b></div><div class="metric">Actual protein<b>${round(t.protein*ratio)} g</b></div><div class="metric">Actual fat<b>${round(t.fat*ratio)} g</b></div></div>`}
['modName','modFinalVolume','modNotes'].forEach(id=>$(id).addEventListener('change',()=>{const k=id==='modName'?'name':id==='modFinalVolume'?'finalVolume':'notes';state.modular[k]=$(id).value;saveState();renderModularSummary()}));$('addModComponentBtn').onclick=()=>{state.modular.components.push(blankComp());saveState();renderModular()};$('addFeedBtn').onclick=()=>{state.modular.feeds.push(blankFeed());saveState();renderModular()};$('saveModularBtn').onclick=()=>{saveState();renderModularSummary()};

$('defaultSource').addEventListener('change',()=>{state.settings.defaultSource=$('defaultSource').value;saveState()});$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ped-nutrition-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});$('importBackupInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{state=merge(defaultState,JSON.parse(await f.text()));saveState();renderPatient();renderMeals();renderFoodDB();renderModular();alert('Restore สำเร็จ')}catch{alert('Backup ไม่ถูกต้อง')}});$('resetBtn').addEventListener('click',()=>{if(confirm('This will permanently delete local patient/case data and custom data on this device. Export a backup first. Continue?')){localStorage.removeItem('pedNutritionStateV4');localStorage.removeItem('pedNutritionStateV3');location.reload()}});

renderPatient();renderMeals();renderFoodDB();renderModular();
